// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdQ-hxJvqgt9-fXiSF0M0X7hGBFazE7as',
    appId: '1:133071346342:web:1bdd5d53bb44f34cc6f267',
    messagingSenderId: '133071346342',
    projectId: 'nellon-vansales',
    authDomain: 'nellon-vansales.firebaseapp.com',
    storageBucket: 'nellon-vansales.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNCb_oCtB0qFb85baM4zrKpKxNQ-L9CZ4',
    appId: '1:133071346342:android:c9f16f4de80e19d6c6f267',
    messagingSenderId: '133071346342',
    projectId: 'nellon-vansales',
    storageBucket: 'nellon-vansales.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZAwJKW8kCDGq7jKpU7l1HVfC8i9hXN1Y',
    appId: '1:133071346342:ios:165289c2578667ddc6f267',
    messagingSenderId: '133071346342',
    projectId: 'nellon-vansales',
    storageBucket: 'nellon-vansales.firebasestorage.app',
    iosClientId: '133071346342-01hh7nckn44cr0taqh4gtsa7rf02negf.apps.googleusercontent.com',
    iosBundleId: 'com.nellon.vansales.vanSales',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZAwJKW8kCDGq7jKpU7l1HVfC8i9hXN1Y',
    appId: '1:133071346342:ios:165289c2578667ddc6f267',
    messagingSenderId: '133071346342',
    projectId: 'nellon-vansales',
    storageBucket: 'nellon-vansales.firebasestorage.app',
    iosBundleId: 'com.nellon.vansales.vanSales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdQ-hxJvqgt9-fXiSF0M0X7hGBFazE7as',
    appId: '1:133071346342:web:220af63159dc13e5c6f267',
    messagingSenderId: '133071346342',
    projectId: 'nellon-vansales',
    authDomain: 'nellon-vansales.firebaseapp.com',
    storageBucket: 'nellon-vansales.firebasestorage.app',
  );
}
